### ISSUE TITLE
More use of Copper Ingot

### ISSUE THREAD

**Issue by 2mal3** [2mal3/2mal3s-Recipes#2]
- Blast Furnace
- ~Piston~
- Hopper
- Smithing Table
- Stonecutter

reference to [Baxmann](https://www.planetminecraft.com/member/baxmann/)s [comment](https://www.planetminecraft.com/data-pack/2mal3-s-recipes/comment/10180227/#reply_10180227) on PlanetMinecraft

**Comment by Baxmann** [comment]
woah, didn't know there was a github. If you'd like, I've already added quite a few of the recipes myself for my world. I can send over the zip if you want.

**Comment by 2mal3** [comment]
Yes 😆. You can send me the file if you want.
