### ISSUE TITLE
Can't craft sticks from bamboo and red dye from beetroot

### ISSUE THREAD

**Issue by satoon10** [2mal3/2mal3s-Recipes#33]
### Minecraft version

1.20.1

### Datapack version

v1.9.1

### Expected Behavior

Get sticks from bamboo and red dye from beetroot

### Actual Behavior

Get green dye from bamboo and beetroot seeds from beetroot

### Reproduction Steps

​

**Comment by 2mal3** [comment]
> Can't craft sticks from bamboo

Couldn't reproduce, probably fixed with the new version



> Can't craft red dye from beetroot

Fixed! You can now get it by cooking beetroot in the oven.
